version: "3.7"
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    stop_signal: SIGTERM
    env_file:
      - .env
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh
      - ~/.gitconfig:/root/.gitconfig
      - vscode-server-volume:/root/.vscode-server
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: script/start-dev
    stop_signal: SIGTERM
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - ./config:/opt/app/config
      - ./lib:/opt/app/lib
      - ./priv:/opt/app/priv
      - ./script:/opt/app/script
      - ./test:/opt/app/test
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: script/start-prod
    stop_signal: SIGTERM
    ports:
      - "5000:5000"
    environment:
      PORT: "5000"
      MIX_ENV: prod
      LOG_LEVEL: info
      SENTRY_LOG_LEVEL: info
    env_file:
      - .env
volumes:
  vscode-server-volume:
