#!/usr/bin/env bash

set -e

case $1 in
"workspace") docker-compose build --force-rm "workspace" ;;
"dev") docker-compose build --force-rm "dev" ;;
"prod") docker-compose build --force-rm "prod" ;;
"load-balancer") docker-compose build --force-rm "load-balancer" ;;
*) docker-compose build --force-rm ;;
esac
