#!/usr/bin/env bash

set -e

echo "Preparing environment..."

echo "Creating environment variables..."

cp .env.example .env

echo ""

echo "Building docker images..."

echo ""

docker-compose build

echo ""

echo "All done!"

echo ""

echo "Run the command below to get started"

echo ""

echo "
$ make start env=dev
"
